src/hooks/data-explorer.ts
src/views/dashboard/data-explorer/components/editor.vue

insert name can replace code at cursor from-to; code format can replace all the line-break

fix(editor): fix insert position and code format

---

src/views/dashboard/data-explorer/components/data-view/index.vue
src/views/dashboard/data-explorer/components/editor.vue
src/views/dashboard/data-explorer/locale/en-US.ts

move clear results button from editor to result tab and change style; change editor height

style(result): move clear button

---

src/hooks/data-explorer.ts
src/store/modules/code-run/index.ts
src/views/dashboard/data-explorer/components/data-view/components/data-chart.vue
src/views/dashboard/data-explorer/components/data-view/config.ts

Make chart xAxis encode name to be the first timestamp name; Add line(smooth) into chart type options;
**Do not merge yet.**
Trying to fix delete tab and chart.

fix: chart xAxis; add smooth line

---

.github/workflows/docker-release.yml

The script is to push docker images to public registries periodically. It is copied from @zyy17 's configuration in db repo.

ci: add nightly docker build

---

src/store/modules/code-run/index.ts
src/views/dashboard/data-explorer/components/data-view/components/data-chart.vue
src/views/dashboard/data-explorer/components/data-view/config.ts

Y type options (of chart form) can support all kinds of number data types now.
Optimising data type rendering #24

fix(result):  support all number data types

---

package-lock.json
package.json
pnpm-lock.yaml
src/views/dashboard/data-explorer/components/editor.vue

fix(editor): code update works if lines are more than 32

---

src/views/dashboard/data-explorer/components/data-view/components/data-grid.vue

fix(table): table head with decimal point not showing

---

package-lock.json
src/components/guide-modal/index.vue
yarn.lock

fix(lock): update package and yarn lock

---

src/api/editor.ts

Create a new pr because pr #93  is way out of date.
Related to issue #104

refactor(api): use axios params

---

.env.production
src/App.vue
src/store/modules/app/index.ts

fix: production mode is not cloud

---

src/App.vue
src/api/editor.ts

To support cloud.
Will deploy later.

fix(api): move db from body to params

---

package-lock.json
package.json
pnpm-lock.yaml

Reverts GreptimeTeam/dashboard#120

Revert "build: bump @codemirror/lang-sql from 6.3.3 to 6.4.0"

---

src/assets/style/button.less
src/assets/style/form.less
src/assets/style/global.less
src/components/navbar/index.vue

style: edit navbar and settings style

---

package-lock.json
package.json
pnpm-lock.yaml

Reverts GreptimeTeam/dashboard#132

Revert "build: bump @codemirror/theme-one-dark from 6.1.0 to 6.1.1"

---

src/assets/style/dataView.less
src/components/navbar/index.vue
src/store/modules/code-run/index.ts
src/views/dashboard/modules/data-view/components/data-chart.vue
src/views/dashboard/modules/data-view/components/data-grid.vue
src/views/dashboard/modules/data-view/index.vue
src/views/dashboard/modules/log.vue
src/views/dashboard/query/editor.vue
src/views/dashboard/scripts/py-editor.vue

Refactor: use one runCode for all code types.
Feat: add new tab for empty result

Feat: Add new tab for empty result

---

src/api/interceptor.ts
src/assets/style/button.less
src/assets/style/form.less
src/assets/style/global.less
src/assets/style/log.less
src/views/dashboard/modules/log.vue
src/views/dashboard/scripts/scripts-list.vue

Add start time for logs.
Reverse logs.
Edit modal style.

feat: Add start time for logs

---

pnpm-lock.yaml
src/assets/style/editor.less
src/assets/style/global.less
src/assets/style/layout.less
src/assets/style/tableList.less
src/views/dashboard/query/editor.vue
src/views/dashboard/scripts/py-editor.vue

#162 
Edit navbar dropdown border radius and font size.

style: UI perfection

---

src/App.vue
src/components/guide-modal/index.vue
src/components/navbar/index.vue
src/config/settings.json
src/layout/default-layout.vue
src/views/dashboard/modules/table-list.vue
src/views/not-found/index.vue

Go back to the last route or query page?

fix: 404 not found page go back

---

src/assets/style/button.less
src/assets/style/editor.less
src/components/global-setting/index.vue
src/components/guide-modal/index.vue
src/store/modules/code-run/index.ts
src/store/modules/code-run/types.ts
src/types/global.ts
src/views/dashboard/modules/table-list.vue
src/views/dashboard/query/editor.vue
src/views/dashboard/scripts/py-editor.vue

feat: Add loading status for code-run and refactor store

---

package.json
pnpm-lock.yaml
src/assets/style/global.less
src/assets/style/log.less
src/views/dashboard/locale/en-US.ts
src/views/dashboard/modules/log.vue
src/views/dashboard/query/editor.vue

feat: Code in logs supports copy-to-clipboard

---

src/assets/style/button.less
src/hooks/query-code.ts
src/views/dashboard/query/editor.vue

style: Add disabled status for buttons

---

src/views/dashboard/modules/data-view/components/data-chart.vue

feat: Select one type as Y by default

---

src/views/dashboard/modules/table-list.vue

refactor: Rename VALUE to FIELD for icons

---

.github/workflows/release.yml

1. Release dashboard
2. Create a PR to GreptimeDB to change the dashboard version.
release dashboard #189

ci: Release dashboard and create PR to DB

---

package-lock.json

* feat: add promQL editor
PromQL edit and execute #103
* feat: add promql api for test
* refactor: add query to promql params
* feat(promql): add start/end/step input for api params
* refactor: edit function name
* feat(promql): add time-range select
* build: update pnpm lockfile
* refactor: route-name and code-type
* fix: change codeType after select queryType
* fix: routeName with correct useRoute
* feat(playground): add view
* feat(playground): auto import files
* feat(playground): refactor log
* feat(playground): refactor log
* refactor(scripts): add playground api
* feat(playground): add loading to run button
* fix(playground): show playground's log in query
* fix(query): show results
* fix(playground): add text
* fix(playground): ts bug
* fix(playground): fix dependencies
* …

feat(playground): add new router view (#195)

---

src/assets/style/global.less

Change popover border-radius.
Fix popover overflow.

style: Fix popover and body overflow

---

src/api/interceptor.ts
src/hooks/python-code.ts
src/hooks/query-code.ts
src/store/modules/code-run/index.ts
src/store/modules/code-run/types.ts

Not the best solution. Need refactoring in the future.

fix: Request error in logs

---

src/hooks/python-code.ts
src/views/dashboard/scripts/py-editor.vue

Name is required when saving script #227
Perhaps we should change the button disabled style.

feat(script): Add validation and disabled status for save-script action

---

src/views/dashboard/playground/code-editor.vue
src/views/dashboard/query/editor.vue

fix: remove replace

---

config/vite.config.base.ts
src/api/status.ts
src/components/navbar/index.vue
src/router/routes/modules/dashboard.ts
src/views/dashboard/status/index.vue

@alili 
could you please take a look when you have time?
I will be very grateful for help with styling

feat: add initial status page implementation

---

index.html
src/api/interceptor.ts
src/assets/style/editor.less
src/assets/style/global.less
src/assets/style/layout.less
src/assets/style/tableList.less
src/components/guide-modal/index.vue
src/components/navbar/index.vue
src/components/refresh-playground-modal/index.vue
src/components/text-copyable.vue
src/components/time-select/index.vue
src/config/settings.json
src/hooks/sider-tabs.ts
src/layout/page-layout.vue
src/locale/en-US.ts
src/store/modules/code-run/types.ts
src/store/modules/database/index.ts
src/store/modules/database/types.ts
src/views/dashboard/locale/en-US.ts
src/views/dashboard/modules/table-list.vue
src/views/dashboard/playground/code-editor.vue
src/views/dashboard/query/editor.vue

feat(tables): add copy to clipboard for copy icon

---

.eslintrc-auto-import.json
src/assets/style/editor.less
src/components/global-setting/index.vue
src/layout/default-layout.vue
src/store/modules/database/index.ts
src/views/dashboard/playground/code-editor.vue
src/views/dashboard/query/editor.vue
src/views/dashboard/scripts/index.vue
src/views/dashboard/scripts/py-editor.vue

- Show guide modal if the environment is `dev` or not dev but the settings config is incomplete.
- Update the config in local storage if the new config input by users is valid.
- Tables should be empty if the network encounters an error in any way.

refactor: guide modal and local storage

---

src/views/dashboard/playground/docs/getting-started.md

docs: add group by time intervals in playground

---

config/vite.config.base.ts
src/components/short-cut/index.vue
src/store/modules/database/index.ts
src/views/dashboard/config.ts
src/views/dashboard/modules/table-list.vue

For compatibility with DB's semantic type changes.

refactor: semantic type map, magic number and generate tree children

---

.eslintrc-auto-import.json
src/components/navbar/index.vue
src/config/settings.json
src/hooks/permission.ts
src/layout/default-layout.vue
src/locale/en-US.ts
src/router/routes/modules/dashboard.ts

refactor(global): generate menu tree; init sidebar menu

---

README.md

Please let me know if the link is incorrect.

fix: broken links in the readme file

---

README.md

The docs of getting started will be updated soon,  Please wait for https://github.com/GreptimeTeam/docs/pull/686

docs: update getting-started document links

---

src/App.vue
src/api/editor.ts
src/assets/style/global.less
src/components/navbar/index.vue
src/components/text-copyable.vue
src/hooks/data-chart.ts
src/views/dashboard/locale/en-US.ts
src/views/dashboard/modules/table-manager.vue
src/views/dashboard/query/index.vue

style: details width and tooltips for buttons

---

src/assets/style/dataView.less
src/components/global-setting/index.vue
src/router/constants.ts
src/router/index.ts
src/router/routes/modules/dashboard.ts
src/views/dashboard/modules/data-view/components/data-grid.vue
src/views/dashboard/modules/data-view/index.vue
src/views/dashboard/modules/log.vue
src/views/dashboard/modules/logs-layout.vue
src/views/dashboard/modules/logs.vue
src/views/dashboard/modules/table-list.vue
src/views/dashboard/modules/table-manager.vue
src/views/dashboard/query/editor.vue
src/views/dashboard/scripts/py-editor.vue
src/views/not-found/index.vue

1. expandable
2. resizable
3. show line-break

feat(table): cell expandable and resizable; show line-break

---

.github/workflows/docker-release.yml
.github/workflows/release.yml

ci: run schedule on upstream only and upgrade actions version

---

src/router/routes/modules/dashboard.ts
src/store/modules/logquery/index.ts
src/views/dashboard/logs/query/index.vue

* logs: query table in current db 
* logs: refresh after db change

fix: load  table in selected db

---

src/store/modules/logquery/index.ts
src/views/dashboard/logs/query/ChartContainer.vue
src/views/dashboard/logs/query/CountChart.vue
src/views/dashboard/logs/query/ExportLog.vue
src/views/dashboard/logs/query/Pagination.vue
src/views/dashboard/logs/query/SQLBuilder.vue
src/views/dashboard/logs/query/TableData.vue
src/views/dashboard/logs/query/Toolbar.vue
src/views/dashboard/logs/query/index.vue

* feat: use icon for cell menu
* fix: typo
* feat: use icon rect
* fix: color
* feat: icon pos and size
* style: menu
* fix: add editing ts column
* refactor: store
* fix: no ts chart
* fix: number convert
* fix: null columns

feat: log refine

---

src/views/dashboard/logs/query/FormView.vue

feat(log-query): support display json field

---

src/store/modules/logquery/index.ts

feat: qoute column name when mixed case

---

src/views/dashboard/query/editor.vue

Failed to execute certain query on dashboard #484

fix(editor): keep origin format for running selected code

---

src/store/modules/logquery/index.ts
src/views/dashboard/logs/query/Toolbar.vue
src/views/dashboard/logs/query/types.ts

* logview: escape for like
* logview: order by ts index column

fix: logquery

---

src/api/pipeline.ts
src/views/dashboard/logs/pipelines/PipeFileView.vue

* upgrade to the new dryrun api
* ui optimization

feat: use new dry run api

---

src/views/dashboard/modules/data-view/index.vue
src/views/dashboard/modules/explain/explain-chart/chart-controls.vue
src/views/dashboard/modules/explain/explain-chart/index.vue
src/views/dashboard/modules/explain/explain-chart/plan-card.vue
src/views/dashboard/modules/explain/explain-chart/tree-view.vue
src/views/dashboard/modules/explain/explain-grid.vue

1. remove node select for chart
2. some styles
3. allow to select stage for chart

feat(explain): allow to select stage for chart

---

src/api/editor.ts
src/api/interceptor.ts
src/views/dashboard/query/editor.vue

For [#6384](https://github.com/GreptimeTeam/greptimedb/pull/6384)

refactor: use csvWithNames as format for export-csv

---

src/components/text-copyable.vue
src/locale/en-US/dashboard.ts
src/locale/zh-CN/dashboard.ts
src/views/dashboard/modules/data-view/index.vue
src/views/dashboard/query/editor.vue

1. auto-explain after paste.
2. allow to import when there are no code in the editor.

perf(explain): auto-explain after paste
